server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://106.14.70.176:5432/postgres
    username: css_ofo_process
    password: CSSChina&20220916&OfoProcess
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.css.mundo.component.mybatis: debug
  config: classpath:logback.xml